### ISSUE TITLE
开源代码时间

### ISSUE THREAD

**Issue by shuowang666** [feifeifeiliu/probtalk#2]
作者您好，请问预计何时开源代码呢？

**Comment by feifeifeiliu** [comment]
感谢您的关注。这周末我们会上传剩余的代码。

**Comment by shuowang666** [comment]
您好，请问“train_vq.sh“等脚本文件位置在哪里呢？

**Comment by shuowang666** [comment]
您好，请问“train_vq.sh”等脚本文件位置在哪里呢？

**Comment by feifeifeiliu** [comment]
> 您好，请问“train_vq.sh”等脚本文件位置在哪里呢？

sorry，刚刚更新上去了
