### ISSUE TITLE
about (b) Train a Predictor

### ISSUE THREAD

**Issue by Mumuwei** [feifeifeiliu/probtalk#3]
Thanks for your wonderful work. 
According to the tutorial, I have completed training (a)Train a PQ-VAE, but the following problem occurred during training (b). 
How can I solve it?
![image](https://github.com/feifeifeiliu/probtalk/assets/44329935/3a4dace4-ec5d-48b7-bbe1-239310ec555a)

**Comment by feifeifeiliu** [comment]
The size of 'vq_layer.embeddings_n' is [num_embeddings, code_dim]. The mismatch issue arises from the inconsistent settings of 'num_embeddings'. To address this, you can change 'Model.code_num' to 128 in the 'config/vq.json' file and re-train the PQ-VAE model. This adjustment should help resolve the problem.

**Comment by Mumuwei** [comment]
Thanks for your reply!
