### ISSUE TITLE
about download pretrained models

### ISSUE THREAD

**Issue by hienhayho** [feifeifeiliu/probtalk#5]
Hello, I can't download pretrained models from your dropbox link, can you check about it ?
<img width="1124" alt="Screenshot 2024-06-27 at 09 45 29" src="https://github.com/feifeifeiliu/probtalk/assets/115549171/d5a5330f-57c8-45e0-85bd-7e465e07985a">

**Comment by feifeifeiliu** [comment]
The dropbox link has been updated.

**Comment by hienhayho** [comment]
thanks so much ^^
